### ISSUE TITLE
Handle `shoot-oidc-service` extension when provisioning kyma [KIM/feature]

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/infrastructure-manager#381]
**Description**

Provisioner should always enable `shoot-oidc-service` feature flag when provisioning kyma runtime
When additional OIDC issuer is requested, provisioner should create this OIDC resource in the provisioned shoot cluster
https://community.sap.com/t5/additional-blogs-by-sap/using-github-actions-openid-connect-in-kubernetes/ba-p/13542513
and configure cluster admin role binding for the subject of the token issued by the  additional issuer. 

**AC**
- [ ] OIDC is part of the technical contract for KIM (= part of Runtime-CR)
- [ ] Following two fields are required in the final Runtime-CR, but for KEB is is not mandatory to set them initially. If one of these field is missing or empty, a default values will be set by KIM (default values are static values in the KIM configuration):
    - [ ] `oidcConfig`  (default value is  Kyma-OIDC provider - it will be only set if no configuration is provided by KEB)
    - [ ] `additionalOidcConfigs` (is a list, if list is empty KIM has to set one default entry to the list)

**Reasons**

It is required for the https://github.com/kyma-project/kyma/issues/18305

**Attachments**
https://github.com/kyma-project/kyma/issues/18519#issuecomment-1918966750
https://github.com/kyma-project/control-plane/tree/main/components/provisioner

Sample resource:
```
apiVersion: authentication.gardener.cloud/v1alpha1
kind: OpenIDConnect
metadata:
  name: actions-oidc
spec:
  issuerURL: https://token.actions.githubusercontent.com
  clientID: my-kubernetes-cluster
  usernameClaim: sub
  usernamePrefix: "actions-oidc:"
  requiredClaims:
    repository: myOrg/myRepo
    workflow: deploy-kubernetes
    ref: refs/heads/main
```
