### ISSUE TITLE
[QG] KIM has to deal with manually added fields by SRE in ShootCR properly (used patching strategy for fields has to be verified in KIM)

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/infrastructure-manager#407]
**Description**

SREs were adding manually fields to the Shoot-Spec (e.g. DNS Configurations, Machine-Controller etc.). These fields were not managed by Provisioner in the past.

Before migrating to KIM, we have to ensure that these fields won't be dropped / modified. This requires a server-side apply for parching Shoot-Specs.

AC:
- [ ] Ensure that updating fields in Shoot-CR is using server-side apply or any other  patch-strategy which isn't removing manually added informations from these ShootCR fields
- [ ] Identify the test cases with SREs which have to be checked before we let KIM manage the cluster completed
    - [ ] Test with manually added DNS configuration in Shoot-CR
    - [ ] Test with manually added Controller in Shoot-CR
- [ ] Run an end-2-end test which manually added fields in SHoot-Spec and ensure KIM isn't removing these data
- [ ] Clarify with SREs if KIM should be the managing system also for these currently manually added fields
    - [ ] If we agree that KIM will manage these fields in the future, create feature-request issues for this missing functionality

**Comment by ebensom** [comment]
examples where SRE made manual adjustments:

1. DNS settings ([core DNS](https://gardener.cloud/docs/gardener/api-reference/core/#core.gardener.cloud/v1beta1.CoreDNS) and node local DNS)
```
spec:
  systemComponents:
    coreDNS:
      autoscaling:
        mode: cluster-proportional
    nodeLocalDNS:
      forceTCPToUpstreamDNS: false
      disableForwardToUpstreamDNS: true
```

2. [Cluster autoscaler](https://gardener.cloud/docs/gardener/api-reference/core/#core.gardener.cloud/v1beta1.ClusterAutoscaler) settings
```
spec:
  kubernetes:
    clusterAutoscaler:
      scaleDownUtilizationThreshold: 0.7
      ignoreDaemonsetsUtilization: true
```

3. API server settings (any of them). One example:
```
spec:
  kubernetes:
    kubeAPIServer:
      defaultNotReadyTolerationSeconds: 180
      defaultUnreachableTolerationSeconds: 180
```

4. kube-controller-manager settings
```
spec:
  kubernetes:
    kubeControllerManager:
      featureGates:
        FEATURE_GATE: true
      nodeMonitorGracePeriod: 3m
```

5. worker group machine controller manager settings:
```
spec:
  provider:
    workers:
    - name: worker-0
      machineControllerManager:
        machineDrainTimeout: 15m
        maxEvictRetries: 2
```
