### ISSUE TITLE
Multiple worker groups [KIM/feature]

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/infrastructure-manager#46]
**Description**
Enable possibility to create multiple worker groups with different machine types, volume types, node labels, annotations, taints.

See Gardener specs:

* Gardener model: https://github.com/gardener/gardener/blob/master/pkg/apis/extensions/v1alpha1/types_worker.go
* Gardener Shoot example: https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml#L30-L152

Current example shoot from Provisioner:

```
 workers:
      - cri:
          name: containerd
        name: cpu-worker-0
        machine:
          type: m5.xlarge
          image:
            name: gardenlinux
            version: 1.2.3
          architecture: amd64
        maximum: 1
        minimum: 1
        maxSurge: 1
        maxUnavailable: 0
        volume:
          type: gp2
          size: 50Gi
        zones:
          - eu-central-1a
        systemComponents:
          allow: true
    workersSettings:
      sshAccess:
        enabled: true
```

AC:
- [x] The value of field `workers` in `RuntimeCR` represents the Kyma worker pool. It is always positioned as FIRST element in the workers-array in Shoot-Spec.
- [x] The values of the field `additonalWorkers` in `RuntimeCR` represents the customer worker pool(s). It is always appended to the `workers` field in Shoot-Spec.
- [x] Before the worker pool feature is rolled out., we have to ensure that each cluster in KCP DEV + STAGE + PROD is using including a worker pool with the name `cpu-worker-1`.

**Reasons**
One size doesn't fit all. Many applications require specific nodes for particular services.

**Relates to**
* https://github.com/kyma-project/kyma/issues/18709

**Comment by tobiscr** [comment]
@pbochynski : QQ - is this feature still relevant? If yes, I will start the alignment also with KEB guys as it needs also their involvment.

**Comment by pbochynski** [comment]
The issue is part of bigger Epic: https://github.com/kyma-project/kyma/issues/18195

**Comment by tobiscr** [comment]
We agreed with @varbanv  and @PK85 to start with a minimal worker pool configuration, probably similar to the parameter we are currently already providing to Google.

**Comment by tobiscr** [comment]
**Open questions**

* Are we allowing 0 worker pools?
* Do we have always a mandatory system-worker pool which is used for Kyma workload to ensure we have at least one compatible worker pool configured?
* What config-parameters are we exposing (arch, min-max pool size, container-runtime etc.)?
* How do we deal if customer selects ARM as worker pool - we have to ensure our workloads won't be installed on this architecture (Affinity for pool required)?


**=> We have to ensure our modules are compatible with all supported worker pool (e.g. Istio could be mandatory for particular workloads even on second worker pool)**

**Comment by tobiscr** [comment]
JFYI:

It's important to set
```
    systemComponents:
          allow: true
``` 
to ensure the pool-nodes gets a label which indicates the related worker pool. This is important for later scheduling rules (via affinity configurations etc.)

**Comment by tobiscr** [comment]
To cover billing requirements, we have to extend the contract of the `RuntimeCR` with 2 new fields: https://github.com/kyma-project/kyma-metrics-collector/issues/89

**Comment by tobiscr** [comment]
Today we aligned the next steps for rolling out multiple worker pools, and it makes sense to distinguish in the `RuntimeCR` between the Kyma worker pool (primarily used by Kyma workloads) and customer worker pools. 

It's meaningful to reflect this differentiation also in the `RuntimeCR` by using a dedicated field for the Kyma worker pool and another field (array) for the customer worker pools.

**Comment by tobiscr** [comment]
Requires https://github.com/kyma-project/infrastructure-manager/issues/396

**Comment by tobiscr** [comment]
From KIM side, we would expect following structure from KEB:

```
...
      workers:
      - cri:
          name: containerd
        machine:
          architecture: amd64
          image:
            name: gardenlinux
            version: 1443.15.0
          type: m5.large
        maxSurge: 3
        maxUnavailable: 0
        maximum: 20
        minimum: 3
        name: cpu-worker-0
        providerConfig:
          apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
          instanceMetadataOptions:
            httpPutResponseHopLimit: 2
            httpTokens: required
          kind: WorkerConfig
        systemComponents:
          allow: true
        volume:
          size: 50Gi
          type: gp2
        zones:
        - eu-central-1b
        - eu-central-1a
        - eu-central-1c
          architecture: amd64
          image:
            name: gardenlinux
            version: 1443.15.0
          type: m5.large
        maxSurge: 3
        maxUnavailable: 0
        maximum: 20
        minimum: 3

      additionalWorkers:   #<< NEW FIELD containing the customer worker pools as array !
      - cri:
          name: containerd
        machine:
          architecture: amd64
          image:
            name: gardenlinux
            version: 1443.15.0
          type: m5.large
        maxSurge: 3
        maxUnavailable: 0
        maximum: 20
        minimum: 3
        name: fancy-workerpool-1
        providerConfig:
          apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
          instanceMetadataOptions:
            httpPutResponseHopLimit: 2
            httpTokens: required
          kind: WorkerConfig
        systemComponents:
          allow: true
        volume:
          size: 50Gi
          type: gp2
        zones:
        - eu-central-1b
        - eu-central-1a
        - eu-central-1c
          architecture: amd64
          image:
            name: gardenlinux
            version: 1443.15.0
          type: m5.large
        maxSurge: 3
        maxUnavailable: 0
        maximum: 20
        minimum: 3
      - cri:
          name: containerd
        machine:
          architecture: amd64
          image:
            name: gardenlinux
            version: 1443.15.0
          type: m5.large
        maxSurge: 3
        maxUnavailable: 0
        maximum: 20
        minimum: 3
        name: fancy-workerpool-2
        providerConfig:
          apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
          instanceMetadataOptions:
            httpPutResponseHopLimit: 2
            httpTokens: required
          kind: WorkerConfig
        systemComponents:
          allow: true
        volume:
          size: 50Gi
          type: gp2
        zones:
        - eu-central-1b
        - eu-central-1a
        - eu-central-1c
          architecture: amd64
          image:
            name: gardenlinux
            version: 1443.15.0
          type: m5.large
        maxSurge: 3
        maxUnavailable: 0
        maximum: 20
        minimum: 3
```
