### ISSUE TITLE
[Threat Modeling]  Check if we process personal data in cluster kubeconfig

### ISSUE THREAD

**Issue by Disper** [kyma-project/infrastructure-manager#54]
**Reason**
We can't store personal data without a reason to be DPP compliant. 

**Acceptance criteria**
- [x] Check if we process personal data in kyma cluster kubeconfig

**Comment by Disper** [comment]
Here's an example of obfuscated kubeconfig:
``` yaml 
apiVersion: v1
clusters:
  - cluster:
    certificate-authority-data: {omitted}
    server: {omitted}
  name: {omitted}
- cluster:
    certificate-authority-data: {omitted}
    server: {omitted}
  name: garden-{omitted}-internal
contexts:
- context:
    cluster: garden-{omitted}-external
    user: garden-{omitted}-external
  name: garden-{omitted}-external
- context:
    cluster: garden-{omitted}-internal
    user: garden-{omitted}-external
  name: garden-{omitted}-internal
current-context: garden-{omitted}-external
kind: Config
preferences: {}
users:
- name: garden-{omitted}-external
  user:
    client-certificate-data: {omitted}
    client-key-data: {omitted}

```
I don't think that we should consider any of those as personal data and we could close this issue. 
WDYT @tobiscr ?
