### ISSUE TITLE
Verify that KIM is not adjusting or overwriting `infrastructureConfig` field in Shoot-Spec (avoid loosing static IPs)

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/infrastructure-manager#583]
´**Description**

We have to ensure that KIM is not adjusting or overwriting configurations provided in the `infrastructureConfig` field in a Shoot-Spec.

This field is usually manually maintained by SREs and we have to make sure that KIM is not manipulating it during the migration or later during reconciliation as it can contain sensitive settings (e.g. static IP configurations for NAT gateways) which can cause massive interruptions.

Example how static IP addresses were configured for a customer who had an incident in the past:

```
kind: InfrastructureConfig
networks:
  vnet:
    cidr: 10.250.0.0/16
  zones:
    - cidr: 10.250.0.0/19
      name: 1
      natGateway:
        enabled: true
        idleConnectionTimeoutMinutes: 4
    - cidr: 10.250.32.0/19
      name: 2
      natGateway:
        enabled: true
        idleConnectionTimeoutMinutes: 4
        ipAddresses:
          - name: shoot--kyma--c-...-nat-gateway-2
            resourceGroup: shoot--kyma--c-....
```

**Expected result**

KIM is migrating the content of the `infrastructureConfig` field comprehensively without any changes. Also during reconciliation are no modifications applied on this field.
