### ISSUE TITLE
Verify that static IP configurations are not dropped or adjusted by KIM

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/infrastructure-manager#587]
**Description**

As risk mitigation of an customer incident, where cluster IPs were dropped, we have to ensure that KIM will not cause any implications with preconfigured static IPs.

What has to be done:

The static IP configuration is usually defined in the Shoot-Spec by referring to the resource group within the `infrastructureConfig` field:

```
kind: InfrastructureConfig
networks:
  vnet:
    cidr: 10.250.0.0/16
  zones:
    - cidr: 10.250.0.0/19
      name: 1
      natGateway:
        enabled: true
        idleConnectionTimeoutMinutes: 4
    - cidr: 10.250.32.0/19
      name: 2
      natGateway:
        enabled: true
        idleConnectionTimeoutMinutes: 4
        ipAddresses:
          - name: shoot--kyma--c-...-nat-gateway-2
            resourceGroup: shoot--kyma--c-....
```

Goal of the task it to confirm that:

* the migration from Provisioner to KIM will not modify anything in this Shoot-Spec
* when KIM is reconciling a cluster, it should not change anything in this section (especially not in field `infrastructureConfig.networks.zones[].natGateway.ipAddresses.resourceGroup`)

**Reasons**

Avoid any change related to static ipAddress configurations which could cause a re-creation of static IP-addresses on Hyperscaler side. This could cause massive implications for customers and their network configuration.

**Attachments**
