### ISSUE TITLE
Spike - Clarify the behaviour of shoot-network-filter

### ISSUE THREAD

**Issue by Disper** [kyma-project/infrastructure-manager#700]
**Description**
Conduct experiments using different `shoot-networking-filter` to understands its behaviour. 

For the conducted experiments I had:
1. Created a GCP cluster
2. Cluster contained the main default `cpu-worker-0` and additional worker `add-1`
3. I was changing its shoot spec configuration according to the [docs](https://github.com/gardener/gardener-extension-shoot-networking-filter/blob/master/docs/usage/shoot-networking-filter.md#ingress-filtering)
4. Waited for reconciliation to be completed
5. For the sake of testing created two workloads
  - function `hello-world` created in `cpu-worker-0` node
  - function `hello-worker1` created in `add-1` node

--- 
Helpful questions from PoC/Spike issue template
- [x] should the Spike include any documentation such as ADR?
No, outcomes will be documented as comments under this issue.
- [ ] is it clear who will benefit from the Spike and how?
Figuring out the `how` part.
- [x] will the final implementation require any migration steps?
No.
- [x] is there a need for alignment with KEB/SRE/other teams? 
Yes, with KEB.
- [x] usually it's worth timeboxing such PoC tasks. What would be a good timebox in this case?
1-2 days should be enough.
- [x] will the final solution need a new repository or any pipelines adjustments?
No.
- [x] are we already aware of any additional challenges related to the release process? E.g. should additional threat modelling sessions be scheduled?
No.
- [ ] will automated tests require any unusual efforts? E.g. complex setup for e2e tests?
Depends if we decide that we want to cover full e2e test of the blackholing feature. 

**Reasons**
Explained already in main epic.

**Attachments**
https://github.com/gardener/gardener-extension-shoot-networking-filter/blob/master/docs/usage/shoot-networking-filter.md#custom-ip

**Comment by Disper** [comment]
### Experiment no.1: Extension explicitly enabled, enabling blackholing for whole shoot

``` yaml
 extensions:
    - type: shoot-networking-filter
      providerConfig:
        egressFilter:
          blackholingEnabled: true
      disabled: false
```

I would expect that I won't be able to reach my test function, however I was 🔴 :
``` bash
curl https://hello.c-8e8e082.dev.kyma.ondemand.com/
Hello World from the Kyma Function hello-world running on nodejs22!⏎
```

**Comment by Disper** [comment]
### Experiment no.2: enabling blackholing for the whole shoot (without explicit disabled: false - as in docs)

``` yaml
 extensions:
    - type: shoot-networking-filter
      providerConfig:
        egressFilter:
          blackholingEnabled: true
```

I would expect that I won't be able to reach my test function, however I was 🔴 :
``` bash
curl https://hello.c-8e8e082.dev.kyma.ondemand.com/
Hello World from the Kyma Function hello-world running on nodejs22!⏎
```

**Comment by Disper** [comment]
### Experiment no.3: using only `custom-ip`and listing my IP address

``` bash
curl ifconfig.me
208.127.58.249⏎
```

``` yaml
    - type: shoot-networking-filter
      providerConfig:
        egressFilter:
          staticFilterList:
            - network: 208.127.58.0/24
              policy: BLOCK_ACCESS
```

I would expect that I won't be able to reach my test function, however I was 🔴 :
``` bash
curl https://hello.c-8e8e082.dev.kyma.ondemand.com/
Hello World from the Kyma Function hello-world running on nodejs22!⏎
```

**Comment by Disper** [comment]
### Experiment no.5: using `worker level blackholing` and  `custom-ip`

``` bash
curl ifconfig.me
208.127.58.249⏎
```

``` yaml
    - type: shoot-networking-filter
      providerConfig:
        egressFilter:
          blackholingEnabled: false
          workers:
            blackholingEnabled: true
            names:
              - add-1
          staticFilterList:
            - network: 208.127.58.0/24
              policy: BLOCK_ACCESS
```

`hello-world` is in the `cpu-worker-0` worker **which does not have blackholing enabled** - I would expect that **I will be able** to reach my test function - and I could 🟢.

``` bash
curl https://hello.c-8e8e082.dev.kyma.ondemand.com/
Hello World from the Kyma Function hello-world running on nodejs22!
```

`hello-worker1` is in the `add-1` worker **which has blackholing enabled** - I would expect that I **won't be able** to reach my test function - and I could 🔴 .

``` bash
curl https://worker1.c-8e8e082.dev.kyma.ondemand.com/
Hello World from the Kyma Function hello-worker1 running on nodejs22!⏎
```

I've double checked that this workload is present in the worker with blackholing enabled (add-1) 
``` bash
kubectl describe pods -n disper hello-worker1-ngzgl-667d987c6d-27fhq | grep Node:
Node:             shoot--kyma-dev--c-8e8e082-add-1-z1-7d975-7nfj2/10.250.0.6
```

**Comment by Disper** [comment]
### Experiment no.6: using `worker level blackholing` without  `custom-ip`

``` yaml
    - type: shoot-networking-filter
      providerConfig:
        egressFilter:
          blackholingEnabled: false
          workers:
            blackholingEnabled: true
            names:
              - add-1
```

Same results [as in previous comment](https://github.com/kyma-project/infrastructure-manager/issues/700#issuecomment-2687807182)

**Comment by Disper** [comment]
### Experiment no.7: using `worker level blackholing` and  `custom-ip` on the worker level

``` bash
curl ifconfig.me
208.127.58.249⏎
```

``` yaml
    - type: shoot-networking-filter
      providerConfig:
        egressFilter:
          blackholingEnabled: false
          workers:
            blackholingEnabled: true
            staticFilterList:
              - network: 208.127.58.0/24
                policy: BLOCK_ACCESS
            names:
              - add-1
      disabled: false
```


Invalid configuration 🔴 

``` yaml
  lastErrors:
    - description: >-
        task "Waiting until extension resources handled after kube-apiserver are
        ready" failed: Error while waiting for Extension
        shoot--kyma-dev--c-8e8e082/shoot-networking-filter to become ready:
        error during reconciliation: Error reconciling Extension: failed to
        decode provider config: strict decoding error: unknown field
        "egressFilter.workers.staticFilterList"
      taskID: Waiting until extension resources handled after kube-apiserver are ready
```

**Comment by Disper** [comment]
While looking at the Gardener API, I discovered that it offers `ALLOW_ACCESS` policy, alongside `BLOCK_ACCESS` ([link](https://github.com/gardener/gardener-extension-shoot-networking-filter/blob/master/pkg/apis/config/types.go#L62-L69)). That could (haven't tested that) potentially offer the possibility of whitelisting IPs.

**Comment by Disper** [comment]
Experiment no.8: using shoot level blackholing and custom-ip on **AZURE** cluster
``` yaml
    - type: shoot-networking-filter
      providerConfig:
        egressFilter:
          blackholingEnabled: true
          staticFilterList:
            - network: 165.1.189.164/24
              policy: BLOCK_ACCESS
```
I would expect that I won't be able to reach my test function - I couldn't 🟢
` Failed to connect to hello-world.c-1507f61.dev.kyma.ondemand.com port 443 after 24517 ms: Couldn't connect to server `
