### ISSUE TITLE
Ingress filtering support for AWS

### ISSUE THREAD

**Issue by Disper** [kyma-project/infrastructure-manager#701]
> The default on AWS is a classic load balancer that replaces the source IP by it's own IP address. Here, a network load balancer has to be configured adding the annotation service.beta.kubernetes.io/aws-load-balancer-type: "nlb" to the service.

See [link](https://github.com/gardener/gardener-extension-shoot-networking-filter/blob/master/docs/usage/shoot-networking-filter.md#ingress-filtering-per-worker-group)

**Comment by Disper** [comment]
Either we should not support it at all or it should be indeed a requirement for customer but documented on our side.

**Comment by tobiscr** [comment]
Test to verify if the Ingress filtering works with AWS:

1. Create via BTP Cockpit a cluster
2. Edit RuntimeCR and enable ingress filtering (because this feature is not yet exposed in the BTP cockpit) + block your source-IP (see [options to block custom-IPs](https://github.com/gardener/gardener-extension-shoot-networking-filter/blob/master/docs/usage/shoot-networking-filter.md#custom-ip))
3. Deploy a workload (e.g. HTTPBin) with a service of type LB and set the annotation described in [Gardener docs](https://github.com/gardener/gardener-extension-shoot-networking-filter/blob/master/docs/usage/shoot-networking-filter.md#ingress-filtering)

**Comment by mvshao** [comment]
## Test setup

- deployed `httpbin` container on Kyma AWS cluster
- created two Services of type `LoadBalancer` pointed to `httpbin` application 
  - `test-lb-1` have annotation `service.beta.kubernetes.io/aws-load-balancer-type: "nlb"`
  - `test-lb-2` does not have an annotation

Each of the test connections to `httpbin` was executed via the LoadBalancer ExternalIP address `....elb.eu-central-1.amazonaws.com`

**Comment by mvshao** [comment]
### Test scenario 1 (no `blackholing`, no `ip restrictistions`) call to `test-lb-1`

```
curl ifconfig.me
83.136.158.205
```

The original public IP of the caller should be visible in `origin` section of HTTP response

```
curl -v a1a9d0d1bf11e490f8d2a57792a99f6f-402115825d963c9d.elb.eu-central-1.amazonaws.com/anything
* Host a1a9d0d1bf11e490f8d2a57792a99f6f-402115825d963c9d.elb.eu-central-1.amazonaws.com:80 was resolved.
* IPv6: (none)
* IPv4: 3.121.38.125
*   Trying 3.121.38.125:80...
* Connected to a1a9d0d1bf11e490f8d2a57792a99f6f-402115825d963c9d.elb.eu-central-1.amazonaws.com (3.121.38.125) port 80
* Request completely sent off
< HTTP/1.1 200 OK
  "json": null,
  "method": "GET",
  "origin": "83.136.158.205",
  "url": "http://a1a9d0d1bf11e490f8d2a57792a99f6f-402115825d963c9d.elb.eu-central-1.amazonaws.com/anything"
}
```

Test passed 🟢

**Comment by mvshao** [comment]
### Test scenario 2 (no `blackholing`, no `ip restrictistions`) call to `test-lb-2`

```
curl ifconfig.me
83.136.158.205
```

The caller's original public IP should not be visible in the `origin` section of HTTP response. It should be LoadBalancerIP

```
curl -v acdf91849bf49493e8da079a498dc39f-299411747.eu-central-1.elb.amazonaws.com/anything
* Host acdf91849bf49493e8da079a498dc39f-299411747.eu-central-1.elb.amazonaws.com:80 was resolved.
* IPv6: (none)
* IPv4: 3.64.200.0
*   Trying 3.64.200.0:80...
* Connected to acdf91849bf49493e8da079a498dc39f-299411747.eu-central-1.elb.amazonaws.com (3.64.200.0) port 80
< HTTP/1.1 200 OK
  "json": null,
  "method": "GET",
  "origin": "10.250.110.1",
  "url": "http://acdf91849bf49493e8da079a498dc39f-299411747.eu-central-1.elb.amazonaws.com/anything"
}
```

Test passed 🟢

**Comment by mvshao** [comment]
### Test scenario 3 (`blackholing`, `ip restrictistions`) call to `test-lb-1`

```
curl ifconfig.me
83.136.158.205
```
```
extensions:
    - type: shoot-networking-filter
      providerConfig:
        egressFilter:
          blackholingEnabled: true
          staticFilterList:
            - network: 83.136.158.205/23
              policy: BLOCK_ACCESS
```
The caller's IP should not be able to reach the destination.

```
curl -v a1a9d0d1bf11e490f8d2a57792a99f6f-402115825d963c9d.elb.eu-central-1.amazonaws.com/anything
* Host a1a9d0d1bf11e490f8d2a57792a99f6f-402115825d963c9d.elb.eu-central-1.amazonaws.com:80 was resolved.
* IPv4: 3.121.38.125
*   Trying 3.121.38.125:80...
curl: (28) Failed to connect to a1a9d0d1bf11e490f8d2a57792a99f6f-402115825d963c9d.elb.eu-central-1.amazonaws.com port 80 after 75055 ms: Couldn't connect to server
```

Test passed 🟢

**Comment by mvshao** [comment]
### Test scenario 4 (`blackholing`, `ip restrictistions`) call to `test-lb-2`

```
curl ifconfig.me
83.136.158.205
```
```
extensions:
    - type: shoot-networking-filter
      providerConfig:
        egressFilter:
          blackholingEnabled: true
          staticFilterList:
            - network: 83.136.158.205/23
              policy: BLOCK_ACCESS
```
The caller's request should not be able to reach the destination. (**_to be clarified_**)

```
curl -v acdf91849bf49493e8da079a498dc39f-299411747.eu-central-1.elb.amazonaws.com/anything
* Host acdf91849bf49493e8da079a498dc39f-299411747.eu-central-1.elb.amazonaws.com:80 was resolved.
* IPv6: (none)
* IPv4: 3.64.200.0
*   Trying 3.64.200.0:80...
* Connected to acdf91849bf49493e8da079a498dc39f-299411747.eu-central-1.elb.amazonaws.com (3.64.200.0) port 80
> GET /anything HTTP/1.1
< HTTP/1.1 200 OK
  "json": null,
  "method": "GET",
  "origin": "10.250.110.1",
  "url": "http://acdf91849bf49493e8da079a498dc39f-299411747.eu-central-1.elb.amazonaws.com/anything"
}
```

Test passed ❓

**Comment by mvshao** [comment]
### Test scenario 5 (multiple worker pools with different blackholing options) - call to `test-lb-3` 

```
curl ifconfig.me
83.136.158.205
```

Shoot configuration

```
 extensions:
    - type: shoot-networking-filter
      providerConfig:
        egressFilter:
          blackholingEnabled: false
          workers:
            blackholingEnabled: true
            names:
              - tess
          staticFilterList:
            - network: 83.136.158.205/23
              policy: BLOCK_ACCESS
```
---

The caller's request should  be able to reach the destination. The call was exectued to unrestricted Service on scheduled on `test` worker pool.

```

```

Test ...

**Comment by mvshao** [comment]
### Test scenario 6 (multiple worker pools with different blackholing options) - call to `test-lb-4` 

```
curl ifconfig.me
83.136.158.205
```

Shoot configuration

```
 extensions:
    - type: shoot-networking-filter
      providerConfig:
        egressFilter:
          blackholingEnabled: false
          workers:
            blackholingEnabled: true
            names:
              - tess
          staticFilterList:
            - network: 83.136.158.205/23
              policy: BLOCK_ACCESS
```
---

The caller's request should  be able to reach the destination. The call was exectued to unrestricted Service on scheduled on `test` worker pool.

```

```

Test ...
