### ISSUE TITLE
KIM has to support Gardener DNS provider

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/infrastructure-manager#714]
**Description**

KIM is currently expecting a custom DNS provider configuration. But we have landscapes which we deploy K8s using Gardener's DNS solution.

KIM should support cluster deployment without a custom DNS configuration. Currently, following error occurs when provisioning a landscape without providing a DNS configuration:

```
{"level":"error","ts":"2025-03-07T13:32:27Z","logger":"setup","msg":"invalid converter configuration","error":"Key: 'Config.ConverterConfig.DNS' Error:Field validation for 'DNS' failed on the 'required' tag","stacktrace":"main.main\n\t/project_workspace/cmd/main.go:202\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272"}
```

KIM has to be adjusted and make the [DNS converter config](https://github.com/kyma-project/infrastructure-manager/blob/main/pkg/config/config.go#L67) optional. As a result,  KIM should generate the below Gardener extension provider config for the shoot: 

```
    - type: shoot-dns-service
      providerConfig:
        apiVersion: service.dns.extensions.gardener.cloud/v1alpha1
        kind: DNSConfig
        syncProvidersFromShootSpecDNS: true
```

**Reasons**

Support landscape which rely on Gardener's DNS provider.

**Attachments**

**Comment by koala7659** [comment]
It is not so straightforward as we use that configuration data from DNS converter config struct in two places in shoot spec

1)  `spec.dns` section Example: 

```
  dns:
    domain: ce70b91.dev.kyma.ondemand.com
    providers:
      - domains:
          include:
            - ce70b91.dev.kyma.ondemand.com
        primary: true
        secretName: aws-route53-secret-dev
        type: aws-route53
```


2) DNS extension data Example:

```
- type: shoot-dns-service
      providerConfig:
        apiVersion: service.dns.extensions.gardener.cloud/v1alpha1
        dnsProviderReplication:
          enabled: true
        kind: DNSConfig
        providers:
          - domains:
              include:
                -<shoot name>.dev.kyma.ondemand.com
            secretName: shoot-dns-service-aws-route53-secret-dev
            type: aws-route53
        syncProvidersFromShootSpecDNS: true
```

What should I put into shoot `spec.dns` section if the DNS converter config is empty?

Example:

```
  dns:
    domain: <shoot_name>.????
    providers:
      - domains:
          include:
            - <shoot_name>.????
        primary: true
        secretName: ???
        type: ????
```

**Comment by tobiscr** [comment]
Copied from Slack (answer from @ebensom ):

How about having the DNSConfig required, but with only the domainPerfix attibute being mandatory:

```
        "dns": {
          "domainPrefix": "my.runtime.domain",
        },
```

If no providerType is defined, It should generate

```
  dns:
    domain: cxxxx1.my.runtime.domain
```

and for dns extension the default providerConfig:

```
    - type: shoot-dns-service
      providerConfig:
        apiVersion: service.dns.extensions.gardener.cloud/v1alpha1
        kind: DNSConfig
        syncProvidersFromShootSpecDNS: true
```

**Comment by Disper** [comment]
How does it look now for cluster which was created on environment which does not provide converter setting of 
`dns.secretName`, `dns.domainPrefix` or `dns.providerType`:

``` yaml
  dns:
    domain: md-dns-az2.kyma-dev.shoot.canary.k8s-hana.ondemand.com

    - type: shoot-dns-service
      providerConfig:
        apiVersion: service.dns.extensions.gardener.cloud/v1alpha1
        kind: DNSConfig
        syncProvidersFromShootSpecDNS: true
```

compared to current behavior where we don't fallback to defaults

``` yaml
  dns:
    domain: xyz.dev.kyma.ondemand.com
    providers:
      - domains:
          include:
            - xyz.dev.kyma.ondemand.com
        primary: true
        secretName: {secret-name}
        type: {provider-type}

    - type: shoot-dns-service
      providerConfig:
        apiVersion: service.dns.extensions.gardener.cloud/v1alpha1
        dnsProviderReplication:
          enabled: true
        kind: DNSConfig
        providers:
          - domains:
              include:
                - xyz.dev.kyma.ondemand.com
            secretName: shoot-dns-service-{secret-name}
            type: {provider-type}
        syncProvidersFromShootSpecDNS: true
```
