### ISSUE TITLE
Expose Shoot-Details on SKR

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/infrastructure-manager#783]
**Description**

The common way of exposing cluster details is via labels on node-resources on SKRs. This approach has several drawbacks:

* The list of labels is continuously growing
* Data which are not node-specific are also added as label to nodes
* Labels are only suitable for simple data structures and cannot be used for complex information

As we have several stakeholders for cluster data (e.g. customers or Busola/Kyma Dashboard), KIM should  expose such details as ConfigMap on SKR clusters.

AC:
- [ ] Propose the structure of the config-map and the exposed data to the team and find a common agreement.
- [ ] During each reconcilation, KIM is generating a ConfigMap with cluster details on the SKR cluster

**Reasons**

KIM is exposing cluster details on SKR during the reconciliation.

**Attachments**

**Comment by mrCherry97** [comment]
Could we also add information about GA and Subaccount name to display this in the Kyma Dashboard? We have a request from the user to display it, and we can't get this informations anywhere from the cluster: https://github.com/kyma-project/lifecycle-manager/issues/2235#issuecomment-2789946582

**Comment by tobiscr** [comment]
> hi [@tobiscr](https://github.com/tobiscr) Could we also add information about GA and Subaccount name to display this in the Kyma Dashboard? We have a request from the user to display it, and we can't get this informations anywhere from the cluster: [kyma-project/lifecycle-manager#2235 (comment)](https://github.com/kyma-project/lifecycle-manager/issues/2235#issuecomment-2789946582)

Hui @mrCherry97 , unfortunately we don't have this information available in RuntimeCR. @kyma-project/gopher - would it be possible to privde this information to Kyma CR?

**Comment by PK85** [comment]
@mrCherry97 we do not have that information on KEB side. Only IDs.

**Comment by Disper** [comment]
I've double-checked with @mrCherry97 that as for today, both comments/issues linked in this ticket are still valid and should be considered during the implementation:
- https://github.com/kyma-project/lifecycle-manager/issues/2235#issuecomment-2789946582 
- https://github.com/kyma-project/busola/issues/3924

**Comment by Disper** [comment]
> @mrCherry97 we do not have that information on KEB side. Only IDs.

@PK85 is it possible that you will receive the names GlobalAccount and Subaccount names and pass them to KIM in the future? The current implementation being introduced in #949 adds only IDs and we wonder if we can enhance that to be more user-friendly.

**Comment by tobiscr** [comment]
<img width="635" alt="Image" src="https://github.com/user-attachments/assets/e1de5375-17c6-4fb5-bde6-fba68815b815" />

**Comment by tobiscr** [comment]
Example:

```
globalAccountID: 4...
infrastructureConfig:
  apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
  kind: InfrastructureConfig
  networks:
    worker: 10.250.0.0/16
    workers: 10.250.0.0/16
subaccountID: 3...
workerPools:
  kyma:
    autoScalerMax: 20
    autoScalerMin: 3
    haZones: true
    machineType: n2-standard-2
    name: cpu-worker-0
```
