### ISSUE TITLE
Synchronise seed data from Gardener Clsuter to KCP.

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/infrastructure-manager#885]

**Comment by m00g3n** [comment]
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kcp-gardener-seed-cache
  namespace: kcp-system
data:
  azure: |
    [
      {
        "name": "westus2",
      },
      {
        "name": "westeurope",
      }
    ]
  aws: |
    [
      {
        "name": "eu-central1",   
      }
    ]
 ```

**Comment by szwedm** [comment]
@m00g3n 
1. We discussed the ConfigMap proposal in the team. We think it would more useful to have one ConfigMap with information about providers. This issue concerns seed regions, we could add more aspects regarding providers and user fast-fail validation in the future. Fast validations meaning KEB validates the input and fails the request without creating Runtime CR. Take a look at the following ConfigMap example:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kcp-kim-providers-information
  namespace: kcp-system
data:
  azure: |-
    seedRegions: # items are unique
      - westus2
      - westeurope
  aws: |-
    seedRegions:
      - eu-central1
```
We were trying to figure out why you used JSON in your example. What do you think about Yaml instead?

2. @PK85 provided a comment in the parent issue: https://github.com/kyma-project/infrastructure-manager/issues/629#issuecomment-2897188977. Please provide an example with data from Production which would be visible for KEB.
